version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: uos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: uos
    ports:
      - "5433:5432"
    volumes:
      - uos_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  uos_postgres_data:
